### ROOT auth
GET http://localhost:4000/user/all

### add user
POST  http://localhost:4000/user/register
Content-Type: application/json 

{
    "email": "test@test",
    "username": "new_user",
    "password": "password1"
}

### login user
POST  http://localhost:4000/user/login
Content-Type: application/json 

{
    "userId": "new_user",
    "password": "password1"
}
