### root route
GET http://localhost:4000/player/ 


### root route
POST http://localhost:4000/player/troop
Content-Type: application/json

{
    "units":  {
        "t3cav": 10,
        "t4cav": 100,
        "t5arch": 1
    }
}